name: Row_B_Baseline_Finetune_CDD11
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 0
classify: true
datasets:
  train_1:
    name: low
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_2:
    name: haze
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/haze
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_3:
    name: rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/rain
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_4:
    name: snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/snow
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_5:
    name: low_haze
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low_haze
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_6:
    name: low_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low_rain
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_7:
    name: low_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low_snow
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_8:
    name: haze_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/haze_rain
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_9:
    name: haze_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/haze_snow
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_10:
    name: low_haze_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low_haze_rain
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  train_11:
    name: low_haze_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_train/CDD-11_train/clear
    dataroot_lq: /data/datasets/CDD-11_train/CDD-11_train/low_haze_snow
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 1
  val_1:
    name: low
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_2:
    name: haze
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/haze
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_3:
    name: rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/rain
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_4:
    name: snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/snow
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_5:
    name: low_haze
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low_haze
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_6:
    name: low_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low_rain
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_7:
    name: low_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low_snow
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_8:
    name: haze_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/haze_rain
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_9:
    name: haze_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/haze_snow
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_10:
    name: low_haze_rain
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low_haze_rain
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
  val_11:
    name: low_haze_snow
    type: PairedImageDataset
    dataroot_gt: /data/datasets/CDD-11_test/clear
    dataroot_lq: /data/datasets/CDD-11_test/low_haze_snow
    io_backend:
      type: disk
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
dataloader:
  phase: train
  use_shuffle: true
  num_worker_per_gpu: 2
  batch_size_per_gpu: 32
  dataset_enlarge_ratio: 1
  pin_memory: true
dataloader_val:
  phase: val
  use_shuffle: false
  num_worker_per_gpu: 1
  batch_size_per_gpu: 1
  pin_memory: true
network_g:
  type: NAFNet
  width: 64
  enc_blk_nums:
  - 1
  - 1
  - 1
  - 28
  middle_blk_num: 1
  dec_blk_nums:
  - 1
  - 1
  - 1
  - 1
  window_size: 8
find_unused_parameters: false
hook_names: decoder
network_dc:
  type: PromptIR_NoImg_DC
  feature_dims:
  - 64
  - 128
  - 256
  - 512
  num_classes: 4
path:
  pretrain_network_g: experiments/Row_B_Baseline_Pretrain_CDD11/models/net_g_latest.pth
  strict_load_g: true
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: 3.0e-04
    weight_decay: 0
    betas:
    - 0.9
    - 0.99
  scheduler:
    type: CosineAnnealingRestartLR
    periods:
    - 500000
    restart_weights:
    - 1
    eta_min: 1.0e-06
  total_iter: 500000
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
val:
  val_freq: 5000.0
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
      image_range: 255.0
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true
      image_range: 255.0
logger:
  print_freq: 100
  save_checkpoint_freq: 5000.0
  use_tb_logger: true
  wandb:
    project: null
